version: "3"
services:
  bot:
    build: .
    restart: always
    environment:
      DISCORD_TOKEN:
      DATABASE_DSN: postgres://discobot:dn7j7uRQYs4Lg6PERegZ2Pvm@db:5432/discobot
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: discobot
      POSTGRES_PASSWORD: dn7j7uRQYs4Lg6PERegZ2Pvm
    volumes:
      - data:/var/lib/postgresql/data
    shm_size: 256M
volumes:
  data:
